{
  self,
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib.modules) mkIf mkMerge;
  inherit (lib.options) mkEnableOption;
  inherit (config.home) homeDirectory;
  cfg = config.dot.ssh;
  yubikeys = config.dot.yubikey.names;
in
{
  options.dot.ssh = {
    enable = mkEnableOption "SSH configuration" // {
      default = config.dot.security.enable;
    };

    enableFido2 = mkEnableOption "YubiKey FIDO2 SSH authentication" // {
      description = ''
        Enable YubiKey FIDO2 SSH authentication.
        When enabled: Only FIDO2 keys are used (maximum security, must have YubiKey).
        When disabled: Only id_ed25519 is used (traditional SSH).

        YubiKeys are automatically discovered from dot.yubikey.names.
      '';
    };
  };

  config = mkIf cfg.enable (mkMerge [
    # ===================================================================
    # Base SSH configuration
    # ===================================================================
    {
      programs.ssh = {
        enable = true;
        enableDefaultConfig = false;

        # All my ssh private keys are generated by `ssh-keygen -t ed25519 -a 256 -C "xxx@xxx"`
        # Config format:
        #   Host — given the pattern used to match against the host name given on the command line.
        #   HostName — specify nickname or abbreviation for host
        #   IdentityFile — the location of your SSH key authentication file for the account.
        # Format in details:
        #   https://www.ssh.com/academy/ssh/config
        matchBlocks = {
          "*" = {
            serverAliveInterval = 180;
            serverAliveCountMax = 3;

            # Key trial order:
            # - If FIDO2 enabled: Only use FIDO2 keys (must have YubiKey)
            # - If FIDO2 disabled: Only use id_ed25519
            identityFile =
              if cfg.enableFido2 then
                # FIDO2 mode: Only YubiKey keys (from dot.yubikey.identifiers)
                (map (name: "${homeDirectory}/.ssh/id_${name}") yubikeys)
              else
                # Traditional mode: Only regular key
                [ "${homeDirectory}/.ssh/id_ed25519" ];

            # Don't auto-add to agent (let FIDO2 work on-demand)
            addKeysToAgent = if cfg.enableFido2 then "no" else "yes";
          };

          "192.168.*" = {
            # allow to securely use local SSH agent to authenticate on the remote machine.
            # It has the same effect as adding cli option `ssh -A user@host`
            forwardAgent = true;
          };

          # NixOS hosts - map hostname to hostname.local for mDNS
          "loki" = {
            hostname = "loki.local";
            forwardAgent = true;
          };

          "sigurd" = {
            hostname = "sigurd.local";
            forwardAgent = true;
          };

          "ymir" = {
            hostname = "ymir.local";
            forwardAgent = true;
          };

          "nidhogg" = {
            hostname = "nidhogg.local";
            forwardAgent = true;
          };

          "github.com" = {
            hostname = "github.com";
            user = "git";
            identityFile =
              if cfg.enableFido2 then
                (map (name: "${homeDirectory}/.ssh/id_${name}") yubikeys)
              else
                [ "${homeDirectory}/.ssh/id_ed25519" ];
            # Specifies that ssh should only use the identity file explicitly configured above
            # required to prevent sending default identity files first.
            identitiesOnly = true;
          };
        };
      };

      home.packages = with pkgs; [
        connect
      ];

      # Link regular SSH public key
      home.file.".ssh/id_ed25519.pub".source = "${self}/secrets/johnson/core/id_ed25519.pub";
    }

    # ===================================================================
    # FIDO2 configuration (when enabled)
    # ===================================================================
    (mkIf cfg.enableFido2 {
      # Install required FIDO2 packages
      home.packages = with pkgs; [
        libfido2 # FIDO2 library and tools
        yubikey-manager # YubiKey configuration tool
      ];

      # Link FIDO2 public key files (only if they exist)
      home.file = mkMerge [
        # YubiKey identification helper script
        {
          ".local/bin/identify-yubikey" = {
            source = "${self}/secrets/johnson/core/keys/identify-yubikey.sh";
            executable = true;
          };
        }

        # Link public key for each YubiKey (if file exists)
        (builtins.listToAttrs (
          builtins.filter (x: x != null) (
            map (
              name:
              let
                pubKeyPath = "${self}/secrets/johnson/core/keys/id_${name}.pub";
              in
              if builtins.pathExists pubKeyPath then
                {
                  name = ".ssh/id_${name}.pub";
                  value = {
                    source = pubKeyPath;
                  };
                }
              else
                null
            ) yubikeys
          )
        ))
      ];

    })
  ]);
}
