{
  lib,
  config,
  ...
}:
let
  inherit (lib.modules)
    mkIf
    mkMerge
    mkDefault
    ;
  inherit (lib.options) mkEnableOption;
  cfg = config.dot.boot;
  isGraphicalMachine = builtins.elem config.dot.device.type [
    "workstation"
    "desktop"
    "laptop"
  ];
in
{
  imports = lib.dot.scanPaths ./.;

  options.dot.boot.initrd = {
    tweaks.enable = mkEnableOption "quality of life tweaks for the initrd stage" // {
      default = true;
    };
    optimizeCompressor =
      mkEnableOption ''
        initrd compression algorithm optimizations for size.
        Enabling this option will force initrd to use zstd (default) with
        level 19 and -T0 (STDIN). This will reduce thee initrd size greatly
        at the cost of compression speed.
        Not recommended for low-end hardware.
      ''
      // {
        default = isGraphicalMachine;
      };
  };

  config.boot = {
    consoleLogLevel = mkDefault 3;

    extraModprobeConfig = mkDefault "options hid_apple fnmode=1";

    # initrd and kernel tweaks
    # read what each parameter or module does before doing so, it will defo break something otherwise
    initrd = mkMerge [
      (mkIf cfg.initrd.tweaks.enable {
        # Verbosity of the initrd
        # disabling verbosity removes only the mandatory messages generated by the NixOS
        verbose = false;

        kernelModules = [
          "nvme"
          "xhci_pci"
          "ahci"
          "btrfs"
          "sd_mod"
          "dm_mod"
        ];

        availableKernelModules = [
          "vmd"
          "usbhid"
          "sd_mod"
          "sr_mod"
          "dm_mod"
          "uas"
          "usb_storage"
          "rtsx_usb_sdmmc"
          "rtsx_pci_sdmmc" # Realtek SD card interface (btw i hate realtek)
          "ata_piix"
          "virtio_pci"
          "virtio_scsi"
          "ehci_pci"
        ];
      })

      (mkIf cfg.initrd.optimizeCompressor {
        compressor = "zstd";
        compressorArgs = [
          "-19"
          "-T0"
        ];
      })
    ];
  };
}
