tailscale_authKey: ENC[AES256_GCM,data:lQuoAq5JaCHjbi3dV5J0b5Jro38WGgdzgIhZcEJEYSljRiZ+KZxBXHN18ErNO2aVDHFafAH5ypdKpQlarlI=,iv:gBS+puGZIpQMziIljgrZGO84kJHCcaoOZGmU8tPUZzk=,tag:fD9Qm/+lXyBFQW3DtPP5Cw==,type:str]
sops:
    age:
        - recipient: age13srgr0k8nkwfh6yuptk9g3ly9aslsatmav4cvje04z58lp8d3d6q0d9g6j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNXRETVpycWRERVJrZE8z
            Qkt3QlhpVHJscHYyOWdpSm8wU0JYUCtlRVFBClA5dmFTY3J0VFVndmhhNCthd1BU
            bHhoWTJaZWwrU0NhVFpMUS9UelpZRkEKLS0tIDgxNjFmbzhTaXB4c09lL2x2a0h1
            dUhVQXdzcm1jNXU1VDMvbTM1cVRWdzAKOoeg3uY2Y7cPuHufNhVxrSH0jfNdu+90
            7vnpPbpDoh+JB02wSQmoI3gLRs1Z8iIwGSTgJILI7SNMnjuhsGVUmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age145r5u0hvnd6xnfgrhgxs0ayp205jsrc2h7aakl4dzmhr78ek9fqs9jfwd2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZVVZcVM2OGRXMCtFZTNv
            SmtZbndTanJReWN0RytOQ3JYYTNwUnVMRFdjCi94eFVUNnQ1aEpLVGhtbDdWYWh5
            b2FncW0wQWxxclgxcjNLdjRrT05NSTgKLS0tIE56NmhvbDAyRjBHR2RyRVNMNGNV
            V09ZYURFZ0NKWlFoRDgrSTFvd2t0OEEKfw+hyuNGs0lCKIJGQSVOXY8caoypZr5h
            VQ47E4lM7P6+A9eS2o3jJCWLMUcA41CjV41OMxrfRUs5HnpxCv6edg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezm8h5js9rl3s23d3xp9ngsapd5anxn7lh8gcd4pafd4ck0alu5qju0lt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1KzZlb1lNRlBSczdqS0Vk
            bk9IWncvREozWTFIVjlDTzA5ekJXN2VWZUcwCk1uV251TGJTQldQOGhZUmdlNFgz
            YkRzQzRHekpBcGZQeXJHSENPN1F0MTgKLS0tIEJvOHNWYVhtaVJyMnNUcmRlc0Vm
            Q0xuZ083N25lOTBGVWczOG92M1UzdncKwyvkIHBvu8YqwJg4auIivM15pBcGv6FC
            LMJR/Wh+2OrvZ2MGcQ2yabJ/k4oQ2d4twiuuVtg2wy2floKEoztzTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f64lg3datsj9l5gq6ca2kuczzg9l2upu0ukavk3ykry5z59c4qnqtsdpgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSy8wd2ZHS1lKZ1ZUd01V
            RU5Scnk2ekNyeE5ZbGpUZDNHKy94YVpVM1gwCjZFUHRsM0pmUTZ6aURDS0hTS0Q1
            V0dvU0tBekNSa1c1a2xoeHZOS0JsaUEKLS0tIEs3UUVJWnFINHZwTysyWWwrdmYr
            SjRackhnZ1hpZUE0MWlUWStrSXZBQVkK2XUmoiOrWLJthN1uwrBuQ7xGaCiuTpn4
            S8ZuRgEqwHVSh43M3MrBYzFsKTvswsrNQQJS8fVq0QPYQHKaMxNUcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m8f0m489vql2p7l4a80ehjh0ae4zgwcnjzv8ngjrsg957yjlcyrq35nvv8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPanA4UXhuRUpKUElmVjAx
            NlNOWi8wVWJIcVlrYVBIMXBkcU0vd2tBV0IwClZkQWsxZFJZakhaUEgybVJjbXg3
            dnhxMXNSZFgrZG5scmpNSncydWsrUXcKLS0tIFdyTXdzQm5hWUQ0WXZscWt3SnhZ
            Yjh3VFRGVnRZK2d2SW0raHZETGlBZlkKEx2hWwICV85N1Q7qunBblKZ5LzgkKb21
            pJ9MNoMc6/flvk3hd3+4WfAWa9iI+wCcsGfUXCWNMiMGkHlYvHIMcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tgkc0ntq7407avss38tsewdur0rc339r5wesatmgp5wn2ya4e9kq4pslme
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TjhGc1N0Z2NpOEZYSVBS
            WGlzQlU5SlU3LzFZTDdNZ0RrK0NxbE4wekZZCnVQVmJDUlJITFhNRGJaSm1weER3
            Y3pyRjJPNEtIQ2huaG1teXJyVFZrak0KLS0tIGxUMURhdytVRTVhOTU5c1B2MVNa
            cGtsTnA1RTNicHlETWZjVHFpZ0RzMWsKblj6VXW9RnPLR2SwFm7MYpq26ymVXP03
            G5JDuzWnuE7M+zMTRmpDQA9stpPrHKXHJtIE6lkPM776fd7Xukfxqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T02:58:35Z"
    mac: ENC[AES256_GCM,data:bkuHlrw/fEC4K2KogN068h7Km32j9CSXJ6vb8kGFJEjZr8vnNwM6fbz2pVuhp39UnMAOCgDTTGPLUsRIk01Hi1dI/3ZShxP53swg4RgFLS8D2FVSA76ZRBUY+pjKpFubd1hwFKFozeYdRjWzhKEms+ypHBN8STi8Zrkdim7hQaQ=,iv:chnVHR/9nRgZQ7W7TVx9VyAlwK8aLD6I9RaSrfMLp9U=,tag:SHi2d5SFhIOpZl8/7fnwRA==,type:str]
    pgp:
        - created_at: "2026-02-27T05:09:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DK+ZqT54JVUESAQdAgyHn0/v88lWvLoWn6GLmRDe9r38gbeHJtrhkLL96OV0w
            ByyTkzty2mAjljHDoM0TNrJ5lfUhCuDwjwRrlRswruS8RZ/aCNsf8yp0H1h7mJxm
            0lwBB+diAcJQTPlrOk+wDnpn66gBGqeypeoekEV8sKNKO0rvjzmDMzYiL1/6FQ5g
            iOuxLtsrdxcFJZrjYv6p/u9NpNrwMkri50LI6+8p8kPlRNgka4PCKUgmWCXhtw==
            =kDYe
            -----END PGP MESSAGE-----
          fp: E23E274D412D4C761A871B1E776C7FC245E58F55
    unencrypted_suffix: _unencrypted
    version: 3.12.2
