{
  lib,
  ...
}:
{
  imports = [ ./persistence.nix ];

  dot.users.michael = {
    fullName = "Michael Shen";
    email = "michael.yy.shen@gmail.com";
    shell = "zsh";
    # generated by `mkpasswd -m scrypt`
    initialHashedPassword = "$7$CU..../....i6N01NHGTP1JT4vXo1eZe.$kv8crbTumL5.J0LfnPrtIcS3H94S4HLMDXnOu203Y06";
    secretsCore = lib.dot.getFile "secrets/michael/core";
    home.imports = [ ./home ];
  };
}
