{
  lib,
  ...
}:
{
  imports = lib.optionals (builtins.pathExists ./persistence.nix) [
    ./persistence.nix
  ];

  dot.users.michael = {
    fullName = "Michael Shen";
    email = "michael.yy.shen@gmail.com";
    shell = "zsh";
    # generated by `mkpasswd -m scrypt`
    initialHashedPassword = "$7$CU..../....5UiVjvZeiXbZjvEWryRuJ.$P0a7/ZfudeBEPSiOJ1NKj4T73OIAnOcY/mwDoIVpeH/";
    home.imports = [ ./home ];
  };
}
