{
  lib,
  ...
}:
let
  inherit (lib.filesystem) listFilesRecursive;
  inherit (lib.lists) forEach optionals;
  secretsCore = lib.dot.getFile "secrets/johnson/core";
  regularKey = secretsCore + "/id_ed25519.pub";
  extraKeysDir = secretsCore + "/keys";
in
{
  imports = lib.optionals (builtins.pathExists ./persistence.nix) [
    ./persistence.nix
  ];

  dot.users.michael = {
    fullName = "Michael Shen";
    email = "michael.yy.shen@gmail.com";
    shell = "zsh";
    # generated by `mkpasswd -m scrypt`
    initialHashedPassword = "$7$CU..../....5UiVjvZeiXbZjvEWryRuJ.$P0a7/ZfudeBEPSiOJ1NKj4T73OIAnOcY/mwDoIVpeH/";
    authorizedKeys =
      optionals (builtins.pathExists regularKey) [
        (builtins.readFile regularKey)
      ]
      ++ optionals (builtins.pathExists extraKeysDir) (
        forEach (lib.filter (path: lib.hasSuffix ".pub" (toString path)) (
          listFilesRecursive extraKeysDir
        )) (key: builtins.readFile key)
      );
    home.imports = [ ./home ];
  };
}
