atuin_key: ""
atuin_keys: ""
atuin_name: ""
atuin_password: ""
github_token: ""
spotify_client_id: ""
tavily_api_key: ""
u2f_keys: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdUcreHNlbXpabTNOWmZV
            SFlEYTRHMGgyNVl6N21oRWVJSTRydWRkYzJrCjNUb0dTME91cWEra283bSs0VVhy
            bHc2SUMzbkRuYThOTmhSaGdTVHNGazQKLS0tIDliNXU1UmlWTnZNaWhZVExmK3ox
            NENDaXlIeU1WWkVja2pMSmlwYnRGQVEKUhNThS9ZlcMgEvQ3PkjpXzss81094+HU
            hapW7kndV2u2fhg0xgtelz1nU3kt/XTfGK6LgcVGGcg7cY8Rtcs2TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1484zve5mrln0gxu8txgxhkw6l7g9svsqre25qy783j9ksrcdqspsxl4926
    lastmodified: "2026-05-17T23:54:36Z"
    mac: ENC[AES256_GCM,data:0Oi/SNlTp921t7xcBCy4Xy5av9hWiScSQQw6m2IeLv4ugyAlX6go/3zZSUU/3RpO8TddVZHjGjYxP4puPpQWWOiSNyQpx1t8k8ZpKoPe43qScDYf8KKlrIEzcCRwGrKOWS9U1A19p7nBkq1PVHbC2jG+Yf72S7zAusLXvVKJMEw=,iv:cyfIsHywmZmLxz4erefGenz7dZWu8V55CjLQiX4yRXc=,tag:nw7YsR2LqItj3OxkaApyZA==,type:str]
    pgp:
        - created_at: "2026-05-17T23:54:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DK+ZqT54JVUESAQdA4xWvvM6B1XFsFLazIbP0qYKNIZZM+nxxUkleLCVLujgw
            X+LsQc86Qrg3pdH4wLxoEs98+tX3ToA4+/lOg5WZOYNmW4IP9CdvSk4ZLQ2nbNJX
            0lwBp60+qTTRpylvtSEdRxFtz4jpAuJswuEVtNyZifWsWnybcSUVcFfnLqtJCl9P
            iESdgROl4yvcw5j2B/OjGaMsXFkmzc6BVwHpjCbk/19rDRUNQp02xFz8TtdKSw==
            =iEjG
            -----END PGP MESSAGE-----
          fp: E23E274D412D4C761A871B1E776C7FC245E58F55
    unencrypted_suffix: _unencrypted
    version: 3.13.0
