{
  lib,
  ...
}:
{
  dot.users.johnson = {
    fullName = "Johnson Hu";
    email = "johnson.wq.hu@gmail.com";
    shell = "fish";
    # generated by `mkpasswd -m scrypt`
    initialHashedPassword = "$y$j9T$UtvejDe22fK.4ok7ZyI1Y/$.vc/kQ3hRFbb2ntOCQQna3CcWWP6dxwtEAE1O9bWcO8";
    secretsCore = lib.dot.getFile "secrets/johnson/core";
    imports = [ ./home ];
  };
}
