{
  lib,
  ...
}:
let
  inherit (lib.filesystem) listFilesRecursive;
  inherit (lib.lists) optionals;
  secretsCore = lib.dot.getFile "secrets/johnson/core";
  regularKey = secretsCore + "/id_ed25519.pub";
  extraKeysDir = secretsCore + "/keys";
in
{
  imports = [ ./persistence.nix ];

  dot.users.johnson = {
    fullName = "Johnson Hu";
    email = "johnson.wq.hu@gmail.com";
    shell = lib.mkDefault "fish";
    # generated by `mkpasswd -m scrypt`
    initialHashedPassword = "$y$j9T$UtvejDe22fK.4ok7ZyI1Y/$.vc/kQ3hRFbb2ntOCQQna3CcWWP6dxwtEAE1O9bWcO8";
    authorizedKeys =
      optionals (builtins.pathExists regularKey) [
        (builtins.readFile regularKey)
      ]
      ++ optionals (builtins.pathExists extraKeysDir) (
        listFilesRecursive extraKeysDir
        |> lib.filter (path: lib.hasSuffix ".pub" (toString path))
        |> map builtins.readFile
      );
    home.imports = [ ./home ];
  };
}
